# Generated by Django 5.0.1 on 2026-02-10 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('marketing', 'marketing'), ('programming', 'Programming'), ('web', 'Web Development'), ('app', 'App Development'), ('game', 'Game Development'), ('database', 'Database Management'), ('network', 'Network Security'), ('cloud', 'Cloud Computing'), ('iot', 'Internet of Things'), ('blockchain', 'Blockchain Technology'), ('cyber', 'Cyber Security'), ('vr', 'Virtual Reality'), ('ar', 'Augmented Reality'), ('mr', 'Mixed Reality'), ('robotics', 'Robotics'), ('bigdata', 'Big Data'), ('datascience', 'Data Science'), ('ai', 'Artificial Intelligence'), ('ml', 'Machine Learning'), ('dl', 'Deep Learning'), ('cv', 'Computer Vision'), ('nlp', 'Natural Language Processing')], max_length=20)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.FileField(blank=True, default='courses/default.jpg', upload_to='courses/')),
            ],
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='System Admin', max_length=30)),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Student', max_length=30)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True, max_length=50)),
                ('username', models.CharField(default='student', max_length=20, unique=True)),
                ('password', models.CharField(blank=True, max_length=16)),
                ('enrolled_courses', models.ManyToManyField(blank=True, related_name='Student', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(auto_now=True)),
                ('reason', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requests', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_requests', to='courses.student')),
            ],
            options={
                'unique_together': {('course', 'student')},
            },
        ),
    ]
