# Generated by Django 5.0.1 on 2026-03-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('programming', 'Programming'), ('web', 'Web Development'), ('app', 'App Development'), ('game', 'Game Development'), ('database', 'Database Management'), ('network', 'Network Security'), ('cloud', 'Cloud Computing'), ('iot', 'Internet of Things'), ('blockchain', 'Blockchain'), ('cyber', 'Cyber Security'), ('vr', 'Virtual Reality'), ('ar', 'Augmented Reality'), ('robotics', 'Robotics'), ('bigdata', 'Big Data'), ('datascience', 'Data Science'), ('ai', 'Artificial Intelligence'), ('ml', 'Machine Learning'), ('dl', 'Deep Learning'), ('cv', 'Computer Vision'), ('nlp', 'NLP'), ('videoedit', 'Video Editing')], max_length=20),
        ),
    ]
