# Generated by Django 5.2 on 2026-03-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_certificate_lessonprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('approved', 'Course Approved'), ('rejected', 'Course Rejected'), ('certificate', 'Certificate Earned'), ('quiz_passed', 'Quiz Passed'), ('enrolled', 'Course Enrolled')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='courses.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
